### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by javiermortiz** [CalebAmes/instructables#1]
- I strongly suggest not to implement Google auth login/Facebook and if you'd really like to implement it, I suggest you save it as a bonus feature.
- I'd need more context on the carousel for feature and why that is a feature on itself. Is the carousel part of the splash page? If that is the case, then I wouldn't consider it part of your 4 features.
- What are blocks for categories?
- Projects is the main feature. I see commenting, adding photos and videos, and searching for projects by keywords in the same line as projects. Those are definitely features on itself. Those 4 (projects, commenting, adding photos/videos, searching) are the recommended features.

**Comment by CalebAmes** [comment]
Thanks Javier! We will get on it.
